# Profile for fast testing using NVENC
arkive_profile_nvenc() {
  FFMPEG_CONTAINER_FORMAT='mp4'
  FFMPEG_VIDEO_ENCODER='nvenc-h264'
  FFMPEG_VIDEO_BITSPERPIXEL='0.05272757201646090534'  # 2560
  FFMPEG_VIDEO_BITDEPTH=8
  FFMPEG_VIDEO_ENCODER_PASSES=1
  FFMPEG_AUDIO_ENCODER='fdk-aac'
  ARKIVE_SUBTITLES=true
  ARKIVE_SUBTITLES_LANG_DEFAULT='eng'
  ARKIVE_SUBTITLES_LANGS=('eng')
  ARKIVE_SUBTITLE_CODEC='webvtt'
}
