#!/usr/bin/env sh

chapter_stream_extractor () {
  # Find chapters if any exist
  hasChapters=$(ffprobe -i $userInput 2>&1 | awk '/Chapter/ { print $2 }')

  # Videos has no chapters
  if [ -z "$hasChapters" ]; then
    echo "Video has no chapters"
  # Video has chapters
  else
    mkvextract \
      chapters \
      --simple $userInput \
      --redirect-output $(temp_directory)/$(filename).xml || \
      { echo "WARNING: Failed to extract chapters from source";\
        return 1; }
  fi
}