#!/usr/bin/env sh


## ffmpeg redirected output [nul]

## [delete video]
if [ -f "$(temp_directory)/$(filename).hvc" ]; then
  rm $(temp_directory)/$(filename).hvc
  echo "Removed $(filename).hvc"
fi

## [delete x265 multi-pass log]
if [ -f "$(temp_directory)/$(filename).stats" ]; then
  rm $(temp_directory)/$(filename).stats
  echo "Removed $(filename).stats"
fi

## [delete audio]
if [ -f "$(temp_directory)/$(filename).opus" ]; then
  rm $(temp_directory)/$(filename).aac
  echo "Removed $(filename).aac"
fi

## [delete subtitles]
if [ -f "$(temp_directory)/$(filename).sub" ]; then
  rm $(temp_directory)/$(filename).sub
  echo "Removed $(filename).sub"
fi
if [ -f "$(temp_directory)/$(filename).idx" ]; then
  rm $(temp_directory)/$(filename).idx
  echo "Removed $(filename).idx"
fi
if [ -f "$(temp_directory)/$(filename).srt" ]; then
  rm $(temp_directory)/$(filename).srt
  echo "Removed $(filename).srt"
fi

## [delete chapter list]
if [ -f "$(temp_directory)/$(filename).xml" ]; then
  rm $(temp_directory)/$(filename).xml
  echo "Removed $(filename).xml"
fi