#!/usr/bin/env sh

audio_encoder () {
  # Encode Audio
  ffmpeg \
  -i "$userInput" \
  -c:a libfdk_aac \
  -map 0:$audioEngStream \
  -ac $audioChannels \
  -b:a $audioBitrate \
  -ar 48000 \
  -y $(temp_directory)/$(filename).aac || \
  { echo -e "${clR}ERROR: audio failed to encode" ; exit 0 ; }
}

video_encoder () {
  # Frames Per Second
  FPS="23.976023976"
  # Get Duration
  totalLength=$(ffprobe "$userInput" 2>&1 | sed -n "s/.* Duration: \([^,]*\), .*/\1/p")
  HRS=$(echo $totalLength | cut -d":" -f1)
  MIN=$(echo $totalLength | cut -d":" -f2)
  SEC=$(echo $totalLength | cut -d":" -f3)
  # Get total number of frames
  totalFrames=$(echo "($HRS*3600+$MIN*60+$SEC)*$FPS" | bc | cut -d"." -f1)
  echo "Estimated total frames: $totalFrames"

  # Number of encoding passes
  passes="2"

  # Initial pass number, DO NOT CHANGE VALUE
  PASS="1"

  while [ $PASS -le $passes ]; do

    echo -e "${clC}Encoding Pass: ${clP}$PASS ${clC}of ${clP}$passes${clD}"

    ## [ffmpeg piped to x265]
    ## TODO: determine if crop height or width are odd numbers and if so
    ##        enable ffmpeg scaling otherwise disable
    ## TODO: make ffmpeg output to $fileName.ffmpeg
    ffmpeg \
      -threads $(cpu_threads) \
      -i "$userInput" \
      -vf "crop=$crop,scale=$cropWidth:trunc(ow/a/2)*2" \
      -r 24000/1001 \
      -pix_fmt yuv420p \
      -f yuv4mpegpipe - 2> nul | \
    x265 \
      --y4m \
      --stats=$tempFilePath/$fileName.stats \
      --threads=$(cpu_cores) \
      --frame-threads=$cpuCores \
      --wpp \
      --ctu=64 \
      --no-cutree \
      --tu-intra-depth=4 \
      --tu-inter-depth=4 \
      --me=2 \
      --cbqpoffs=3 \
      --crqpoffs=3 \
      --psy-rd=0.15 \
      --subme=7 \
      --merange=60 \
      --ref=4 \
      --bframes=3 \
      --b-pyramid \
      --b-adapt=2 \
      --bframe-bias=0 \
      --b-intra \
      --weightb \
      --weightp \
      --bitrate=1024 \
      --vbv-init=0.9 \
      --vbv-bufsize=31250 \
      --vbv-maxrate=31250 \
      --no-slow-firstpass \
      --pass=$PASS \
      --keyint=250 \
      --min-keyint=23 \
      --rc-lookahead=60 \
      --no-constrained-intra \
      --aq-mode=0 \
      --lft \
      --sao-lcu-opt=1 \
      --cbqpoffs=-3 \
      --crqpoffs=-3 \
      --rect \
      --amp \
      --max-merge=5 \
      --no-early-skip \
      --no-tskip \
      --hash=2 \
      -f 0 \
      -o "$(temp_directory)/$(filename).hvc" - || \
      { echo "ERROR: video encoding failed";exit 0; }

    # Finished encoding
    if [ $PASS == $passes ]; then
      echo
      echo "Encoding complete"
    # Not finised encoding
    else 
      echo
    fi

    # Increment pass count
    PASS="$(( $PASS + 1 ))"
  done
}