#!/usr/bin/env sh

muxer () {
  # mkvmerge
  # -o "$rar_variable-s.mkv"
  # "--default-track" "0:yes"
  # "--forced-track" "0:no"
  # "--language" "1:eng"
  # "--track-name"
  # "1:English"
  # "--default-track"
  # "1:yes"
  # "--forced-track"
  # "1:no"
  # "--language" "2:eng"
  # "--default-track" "2:yes" "--forced-track"
  # "2:no" "-a" "1" "-d" "0" "-s" "2" "-T" "--no-global-tags"
  # "--no-chapters" "(" "$rlsname_variable.mkv" ")"
  # "--track-order" "0:0,0:1,0:2" "--split" "parts:00:01:30-00:02:30"

  ## [check for chaper file]
  if [ -f "$(temp_directory)/$(filename).xml" ]; then
    muxChapters="--chapters $(temp_directory)/$(filename).xml"
  else
    muxChapters=""
  fi

  ## [check for subtitle file]
  if [ -f "$(temp_directory)/$(filename).srt" ]; then
    muxSubtitles="$(temp_directory)/$(filename).srt"
  else
    muxSubtitles=""
  fi

  ## TODO: find audio language and set videolanguage to audiolanguage
  mkvmerge \
      -o $(output_directory)/$(filename).mkv \
      --title $(filename) \
      -A $(temp_directory)/$(filename).hvc \
      $muxChapters \
      $muxSubtitles \
      $(temp_directory)/$(filename).aac
}
