#!/usr/bin/env sh


arkhive_usage () {
    eval "printf \"\n\${clC}ARKhive version:\${clG} ${VERSION}
\${clC}Automated video encoding according to Chlorm's ARK specifications.

Usage: \${clD}arkhive [\${clU}\${clP}OPTIONS\$clD] \${clU}\${clP}FILE\$clD [\${clU}\${clP}OPTIONS\$clD]\$clD
    \$clG-i|--input  \${clU}\${clP}FILE\$clD          \$clY*\$clD - set input file\$clD
    \$clG-o|--output \${clU}\${clP}DIRECTORY\$clD       - set output directory\$clD
    \$clG-t|--temp   \${clU}\${clP}DIRECTORY\$clD       - set temp directory\$clD
    \$clG-h|--help\$clD                   - print this message
    \$clG-v|--version\$clD                - print version\n\n\""
}