#!/usr/bin/env bash

# Arkive h.264/AVC main profile, ACC HE-AAC, WebVTT

FFMPEG_CONTAINER_FORMAT='mp4'
FFMPEG_VIDEO_ENCODER='x265'
FFMPEG_VIDEO_BITSPERPIXEL='0.05272757201646090534'  # 2560
FFMPEG_VIDEO_BITDEPTH=10
FFMPEG_VIDEO_ENCODER_PASSES=1
FFMPEG_VIDEO_FRAMERATE='source'
FFMPEG_AUDIO_ENCODER='fdk-aac'
ARKIVE_SUBTITLES=true
ARKIVE_SUBTITLES_LANG_DEFAULT='eng'
ARKIVE_SUBTITLES_LANGS=('eng')
ARKIVE_SUBTITLE_CODEC='webvtt'
